### ISSUE TITLE
Running Todo

### ISSUE THREAD

**Issue by rawkit1** [rawkit1/VirtualPi#1]
- [ ] Research on image splitting

  - [ ] Req hardware list (sensors, etc)

  - [ ] Strip down headset and mount Pi

  - [ ] Diagram

  - [ ] Image splitting code

  - [ ] Research on tracking

  - [ ] Financial report

  - [ ] Purchase parts

  - [ ] Tracking code

  - [ ] Basic Assembly

  - [ ] Tutorial
